/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/swordShield-transformed.glb')
  let hasCape = props.hasCape;
  let clothingColor = props.clothingColor
  let armorColor = props.armorColor
  let weaponColor = props.weaponColor
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.254, -0.019]} rotation={[0.17, 0, 0]}>
        <group position={[0, 0.076, 0]} rotation={[-0.119, 0, 0]}>
          <group position={[0, 0.079, 0]} rotation={[-0.108, 0, 0]}>
            <group position={[0, 0.058, 0]} rotation={[-0.005, 0, 0]}>
              <group position={[0, 0.105, 0]} rotation={[0.23, 0, 0]} />
              <group position={[0.028, 0.05, 0.029]} rotation={[-1.457, -0.104, -1.322]}>
                <group position={[-0.002, 0.09, -0.001]} rotation={[0.934, 1.475, -1.218]}>
                  <group position={[0, 0.116, 0]} rotation={[0.344, -0.211, -0.057]}>
                    <group position={[0, 0.11, 0]} rotation={[-0.167, 0.131, -0.073]}>
                      <group position={[-0.002, 0.02, 0.012]} rotation={[0.549, 1.519, -0.344]}>
                        <group position={[0, 0.036, 0]} rotation={[0.121, 0.206, -0.279]}>
                          <group position={[0, 0.021, 0]} rotation={[0.25, -0.105, 0.038]} />
                        </group>
                        <group position={[-0.004, 0.002, 0.005]} rotation={[-1.207, 0.359, 1.587]}>
                          <group position={[0, 0.016, 0]} rotation={[0.319, -0.168, -0.07]} />
                        </group>
                      </group>
                      <group position={[-0.004, 0.021, 0.003]} rotation={[-1.054, 1.503, 0.909]}>
                        <group position={[0, 0.032, 0]} rotation={[0.17, 0.121, 0.077]}>
                          <group position={[0, 0.027, 0]} rotation={[0.102, 0.059, 0.003]} />
                        </group>
                      </group>
                      <group position={[-0.002, 0.017, -0.014]} rotation={[-2.463, 1.396, 2.171]}>
                        <group position={[0, 0.035, 0]} rotation={[0.345, -0.269, 0.136]}>
                          <group position={[0, 0.028, 0]} rotation={[0.094, -0.004, 0.011]} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group position={[-0.028, 0.05, 0.029]} rotation={[-1.457, 0.104, 1.322]}>
                <group position={[0.002, 0.09, -0.001]} rotation={[0.934, -1.475, 1.218]}>
                  <group position={[0, 0.116, 0]} rotation={[0.344, 0.211, 0.057]}>
                    <group position={[0, 0.11, 0]} rotation={[-0.167, -0.131, 0.073]}>
                      <group position={[0.002, 0.02, 0.012]} rotation={[0.549, -1.519, 0.344]}>
                        <group position={[0, 0.036, 0]} rotation={[0.121, -0.206, 0.279]}>
                          <group position={[0, 0.021, 0]} rotation={[0.25, 0.105, -0.038]} />
                        </group>
                        <group position={[0.004, 0.002, 0.005]} rotation={[-1.207, -0.359, -1.587]}>
                          <group position={[0, 0.016, 0]} rotation={[0.319, 0.168, 0.07]} />
                        </group>
                      </group>
                      <group position={[0.004, 0.021, 0.003]} rotation={[-1.054, -1.503, -0.909]}>
                        <group position={[0, 0.032, 0]} rotation={[0.17, -0.121, -0.077]}>
                          <group position={[0, 0.027, 0]} rotation={[0.102, -0.059, -0.003]} />
                        </group>
                      </group>
                      <group position={[0.002, 0.017, -0.014]} rotation={[-2.463, -1.396, -2.171]}>
                        <group position={[0, 0.035, 0]} rotation={[0.345, 0.269, -0.136]}>
                          <group position={[0, 0.028, 0]} rotation={[0.094, 0.004, -0.011]} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group position={[0.081, 0.008, -0.099]} rotation={[-1.09, 1.441, -1.758]}>
                <group position={[0, 0.037, 0]} rotation={[-0.066, 0.008, -0.24]}>
                  <group position={[0, 0.089, 0]} rotation={[0.028, 0.001, -0.008]}>
                    <group position={[0, 0.117, 0]} rotation={[0.011, 0.003, 0.181]} />
                  </group>
                </group>
              </group>
              <group position={[-0.081, 0.008, -0.099]} rotation={[-1.09, -1.441, 1.758]}>
                <group position={[0, 0.037, 0]} rotation={[-0.066, -0.008, 0.24]}>
                  <group position={[0, 0.089, 0]} rotation={[0.028, -0.001, 0.008]}>
                    <group position={[0, 0.117, 0]} rotation={[0.011, -0.003, -0.181]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group position={[0.08, 0.015, 0.013]} rotation={[2.863, -0.007, -0.038]}>
          <group position={[0, 0.123, 0]} rotation={[0.254, 0.02, -0.003]}>
            <group position={[0, 0.098, 0]} rotation={[-0.986, -0.033, 0.02]} />
          </group>
        </group>
        <group position={[-0.08, 0.015, 0.013]} rotation={[2.863, 0.007, 0.038]}>
          <group position={[0, 0.123, 0]} rotation={[0.254, -0.02, 0.003]}>
            <group position={[0, 0.098, 0]} rotation={[-0.986, 0.033, -0.02]} />
          </group>
        </group>
      </group>
      <group rotation={[0, 1.571, 0]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, 0.019, 0.254]} rotation={[1.741, 0, 0]}>
            <group position={[0, 0.076, 0]} rotation={[-0.119, 0, 0]}>
              <group position={[0, 0.079, 0]} rotation={[-0.09, 0, 0]}>
                <group position={[0, 0.058, 0]} rotation={[-0.041, 0, 0]}>
                  <group position={[0.028, 0.05, 0.029]} rotation={[-1.457, -0.104, -1.322]}>
                    <group
                      position={[-0.002, 0.09, -0.001]}
                      rotation={[2.311, 0.93, 3.004]}
                      scale={[0.989, 0.989, 0.989]}>
                      <group position={[0, 0.116, 0]} rotation={[1.231, 0, 0]}>
                        <group
                          position={[0, 0.11, 0]}
                          rotation={[0.456, -0.297, -0.205]}
                          scale={[1.011, 1.011, 1.011]}
                        />
                        <group scale={1.011} />
                        <group position={[0, 0.055, 0]} rotation={[0, -0.123, 0]} scale={[1.011, 1.011, 1.011]} />
                      </group>
                      <group position={[0, 0.058, 0]} rotation={[0, -0.28, 0]} scale={[1.012, 1.012, 1.012]} />
                    </group>
                    <group position={[-0.002, 0.09, -0.001]} rotation={[-0.114, -0.026, 1.323]}>
                      <group rotation={[2.071, -0.188, -2.447]} />
                      <group rotation={[1.705, 0.137, -1.761]}>
                        <group position={[0, 0.116, 0]} rotation={[0.36, 0, 0]}>
                          <group position={[0, 0.11, 0]} rotation={[-0.14, 0, -0.129]} />
                        </group>
                      </group>
                      <group rotation={[2.071, -0.188, -2.447]} scale={[0.989, 0.989, 0.989]} />
                    </group>
                    <group position={[-0.002, 0.09, -0.001]} rotation={[2.773, 1.42, 2.564]} />
                    <group
                      position={[-0.002, 0.09, -0.001]}
                      rotation={[2.773, 1.42, 2.564]}
                      scale={[1.006, 0.989, 1.006]}>
                      <group position={[0, 0.058, 0]} rotation={[0, 0.229, 0]}>
                        <group position={[0, 0.058, 0]} rotation={[1.244, 0.092, -0.264]} scale={[1, 0.985, 1.015]}>
                          <group position={[0, 0.055, 0]} rotation={[0, -0.123, 0]}>
                            <group
                              position={[0, 0.055, 0]}
                              rotation={[0.443, -0.186, -0.261]}
                              scale={[0.996, 1.007, 0.997]}>
                              <group position={[-0.005, 0.02, 0.012]} rotation={[0.101, 1.301, 0.107]}>
                                <group
                                  position={[0, 0.036, 0]}
                                  rotation={[0.16, 0.131, -0.283]}
                                  scale={[0.995, 1.011, 0.995]}>
                                  <group
                                    position={[0, 0.021, 0]}
                                    rotation={[0.562, 0.007, 0.022]}
                                    scale={[1.005, 0.994, 1.001]}
                                  />
                                </group>
                                <group position={[-0.004, 0.002, 0.005]} rotation={[-1.307, 0.356, 1.622]}>
                                  <group position={[0, 0.016, 0]} rotation={[0.828, 0.068, -0.119]} />
                                </group>
                                <group position={[0, 0.036, 0]} rotation={[0.178, 0.126, -0.286]}>
                                  <group position={[0, 0.021, 0]} rotation={[0.544, 0.007, 0.022]}>
                                    <group position={[0, 0.019, 0]} rotation={[0.265, -0.014, -0.047]} />
                                  </group>
                                </group>
                                <group
                                  position={[0, 0.036, 0]}
                                  rotation={[0.16, 0.131, -0.283]}
                                  scale={[0.995, 1.011, 0.995]}>
                                  <group
                                    position={[0, 0.021, 0]}
                                    rotation={[0.562, 0.007, 0.022]}
                                    scale={[1.005, 0.994, 1.001]}
                                  />
                                </group>
                                <group position={[-0.004, 0.002, 0.005]} rotation={[-1.307, 0.356, 1.622]}>
                                  <group position={[0, 0.016, 0]} rotation={[0.828, 0.068, -0.119]}>
                                    <group position={[0, 0.02, 0]} rotation={[0.66, 0.04, 0.062]} />
                                  </group>
                                </group>
                              </group>
                              <group position={[-0.001, 0.021, 0.017]} rotation={[-1.655, 0.307, 3.013]}>
                                <group position={[0, 0.016, 0]} rotation={[0.828, 0.068, -0.119]} />
                              </group>
                              <group position={[-0.004, 0.021, 0.003]} rotation={[-0.228, 1.306, 0.077]}>
                                <group
                                  position={[0, 0.032, 0]}
                                  rotation={[0.278, 0.167, 0.112]}
                                  scale={[0.997, 1.005, 0.997]}>
                                  <group
                                    position={[0, 0.027, 0]}
                                    rotation={[0.396, 0.003, 0.01]}
                                    scale={[1.003, 0.996, 1.001]}
                                  />
                                </group>
                                <group position={[0, 0.032, 0]} rotation={[0.261, 0.165, 0.115]}>
                                  <group position={[0, 0.027, 0]} rotation={[0.413, 0.003, 0.011]}>
                                    <group position={[0, 0.023, 0]} rotation={[0.323, -0.008, -0.024]} />
                                  </group>
                                </group>
                                <group
                                  position={[0, 0.032, 0]}
                                  rotation={[0.278, 0.167, 0.112]}
                                  scale={[0.997, 1.005, 0.997]}>
                                  <group
                                    position={[0, 0.027, 0]}
                                    rotation={[0.396, 0.003, 0.01]}
                                    scale={[1.003, 0.996, 1.001]}
                                  />
                                </group>
                              </group>
                              <group position={[0.001, 0.017, -0.014]} rotation={[-0.894, 1.43, 0.589]}>
                                <group
                                  position={[0, 0.034, 0]}
                                  rotation={[0.468, -0.4, 0.184]}
                                  scale={[0.964, 1.077, 0.964]}>
                                  <group
                                    position={[0, 0.028, 0]}
                                    rotation={[0.375, -0.001, -0.003]}
                                    scale={[1.038, 0.944, 1.024]}
                                  />
                                </group>
                                <group position={[0, 0.034, 0]} rotation={[0.448, -0.403, 0.176]}>
                                  <group position={[0, 0.03, 0.001]} rotation={[0.392, -0.001, -0.003]}>
                                    <group position={[0, 0.018, 0]} rotation={[0.276, 0.002, 0.006]} />
                                  </group>
                                </group>
                                <group
                                  position={[0, 0.034, 0]}
                                  rotation={[0.468, -0.4, 0.184]}
                                  scale={[0.964, 1.077, 0.964]}>
                                  <group
                                    position={[0, 0.028, 0]}
                                    rotation={[0.375, -0.001, -0.003]}
                                    scale={[1.038, 0.944, 1.024]}
                                  />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group position={[-0.028, 0.05, 0.029]} rotation={[-1.457, 0.104, 1.322]}>
                    <group
                      position={[0.002, 0.09, -0.001]}
                      rotation={[2.808, -0.656, -2.469]}
                      scale={[0.983, 0.983, 0.983]}>
                      <group position={[0, 0.116, 0]} rotation={[1.645, 0, 0]} scale={[0.999, 0.999, 0.999]}>
                        <group position={[0, 0.11, 0]} rotation={[0.027, 0.46, -0.023]} scale={[1.018, 1.018, 1.018]} />
                        <group scale={[1.018, 1.018, 1.018]} />
                        <group position={[0, 0.055, 0]} rotation={[0, 0.23, 0]} scale={[1.018, 1.018, 1.018]} />
                      </group>
                      <group position={[0, 0.058, 0]} rotation={[0, 0.467, 0]} scale={[1.017, 1.017, 1.017]} />
                    </group>
                    <group position={[0.002, 0.09, -0.001]} rotation={[-0.114, 0.026, -1.323]}>
                      <group rotation={[2.48, 0.023, 2.577]} />
                      <group rotation={[1.705, -0.137, 1.761]}>
                        <group position={[0, 0.116, 0]} rotation={[0.36, 0, 0]}>
                          <group position={[0, 0.11, 0]} rotation={[-0.14, 0, 0.129]} />
                        </group>
                      </group>
                      <group rotation={[2.48, 0.023, 2.577]} scale={[0.983, 0.983, 0.983]} />
                    </group>
                    <group position={[0.002, 0.09, -0.001]} rotation={[-2.378, -1.054, -1.589]} />
                    <group
                      position={[0.002, 0.09, -0.001]}
                      rotation={[-2.378, -1.054, -1.589]}
                      scale={[1.008, 0.983, 1.008]}>
                      <group position={[0, 0.058, 0]} rotation={[0, -0.316, 0]}>
                        <group position={[0, 0.058, 0]} rotation={[1.637, 0.033, 0.466]} scale={[1, 0.974, 1.026]}>
                          <group position={[0, 0.055, 0]} rotation={[0, 0.23, 0]}>
                            <group
                              position={[0, 0.055, 0]}
                              rotation={[0.025, 0.23, -0.017]}
                              scale={[0.991, 1.018, 0.991]}>
                              <group position={[0.005, 0.02, 0.012]} rotation={[0.101, -1.301, -0.107]}>
                                <group position={[0, 0.036, 0]} rotation={[0.472, -0.035, 0.309]}>
                                  <group position={[0, 0.021, 0]} rotation={[1.265, -0.019, -0.012]} />
                                </group>
                                <group
                                  position={[0.004, 0.002, 0.005]}
                                  rotation={[-0.877, -0.217, -2.18]}
                                  scale={[1.019, 0.963, 1.019]}>
                                  <group
                                    position={[0, 0.016, 0]}
                                    rotation={[1.334, -0.081, -0.101]}
                                    scale={[0.873, 1.244, 0.921]}
                                  />
                                </group>
                                <group position={[0, 0.036, 0]} rotation={[0.472, -0.035, 0.309]}>
                                  <group position={[0, 0.021, 0]} rotation={[1.265, -0.019, -0.012]}>
                                    <group position={[0, 0.019, 0]} rotation={[0.986, 0.041, 0.026]} />
                                  </group>
                                </group>
                                <group position={[0, 0.036, 0]} rotation={[0.472, -0.035, 0.309]}>
                                  <group position={[0, 0.021, 0]} rotation={[1.265, -0.019, -0.012]} />
                                </group>
                                <group position={[0.004, 0.002, 0.005]} rotation={[-1.219, -0.624, -2.288]}>
                                  <group position={[0.001, 0.014, -0.008]} rotation={[0.872, -0.109, 0.205]}>
                                    <group position={[0.008, 0.024, -0.001]} rotation={[0.69, -0.042, -0.061]} />
                                  </group>
                                </group>
                              </group>
                              <group
                                position={[0.001, 0.021, 0.017]}
                                rotation={[-1.421, -0.691, 2.704]}
                                scale={[1.019, 0.963, 1.019]}>
                                <group
                                  position={[0, 0.016, 0]}
                                  rotation={[1.334, -0.081, -0.101]}
                                  scale={[0.873, 1.244, 0.921]}
                                />
                              </group>
                              <group position={[0.004, 0.021, 0.003]} rotation={[-0.228, -1.306, -0.077]}>
                                <group position={[0, 0.032, 0]} rotation={[0.555, -0.218, 0.005]}>
                                  <group
                                    position={[0, 0.027, 0]}
                                    rotation={[1.527, -0.026, -0.072]}
                                    scale={[1.032, 0.939, 1.032]}
                                  />
                                </group>
                                <group position={[0, 0.032, 0]} rotation={[0.555, -0.218, 0.005]}>
                                  <group position={[0, 0.027, 0]} rotation={[1.119, -0.009, -0.006]}>
                                    <group position={[0.002, 0.02, 0.009]} rotation={[1.029, 0.021, 0.013]} />
                                  </group>
                                </group>
                                <group position={[0, 0.032, 0]} rotation={[0.555, -0.218, 0.005]}>
                                  <group
                                    position={[0, 0.027, 0]}
                                    rotation={[1.527, -0.026, -0.072]}
                                    scale={[1.032, 0.939, 1.032]}
                                  />
                                </group>
                              </group>
                              <group position={[-0.001, 0.017, -0.014]} rotation={[-0.894, -1.43, -0.589]}>
                                <group position={[0, 0.035, 0]} rotation={[0.768, 0.332, -0.292]}>
                                  <group
                                    position={[0, 0.028, 0]}
                                    rotation={[1.283, 0.059, 0.635]}
                                    scale={[0.959, 1.087, 0.959]}
                                  />
                                </group>
                                <group position={[0, 0.035, 0]} rotation={[0.768, 0.332, -0.292]}>
                                  <group position={[0, 0.028, 0]} rotation={[1.113, 0.002, 0.002]}>
                                    <group position={[-0.012, 0.016, 0.003]} rotation={[0.997, -0.005, -0.003]} />
                                  </group>
                                </group>
                                <group position={[0, 0.035, 0]} rotation={[0.768, 0.332, -0.292]}>
                                  <group
                                    position={[0, 0.028, 0]}
                                    rotation={[1.283, 0.059, 0.635]}
                                    scale={[0.959, 1.087, 0.959]}
                                  />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group position={[0.081, 0.008, -0.099]} rotation={[-1.09, 1.441, -1.758]}>
                    <group position={[0, 0.037, 0]} rotation={[-0.066, 0.008, -0.24]}>
                      <group position={[0, 0.089, 0]} rotation={[0.028, 0.001, -0.008]}>
                        <group position={[0, 0.117, 0]} rotation={[0.011, 0.003, 0.181]} />
                      </group>
                    </group>
                  </group>
                  <group position={[-0.081, 0.008, -0.099]} rotation={[-1.09, -1.441, 1.758]}>
                    <group position={[0, 0.037, 0]} rotation={[-0.066, -0.008, 0.24]}>
                      <group position={[0, 0.089, 0]} rotation={[0.028, -0.001, 0.008]}>
                        <group position={[0, 0.117, 0]} rotation={[0.011, -0.003, -0.181]} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
            <group rotation={[-1.701, -0.495, -1.851]} />
            <group rotation={[-1.701, 0.495, 1.851]} />
            <group position={[0.08, 0.015, 0.013]} rotation={[2.863, 0.005, -0.038]}>
              <group position={[0, 0.123, 0]} rotation={[0.253, 0, 0]}>
                <group position={[0, 0.098, 0]} rotation={[-0.986, -0.028, 0.027]}>
                  <group position={[0, 0.062, 0]} rotation={[2.412, 0, 0.003]} />
                </group>
                <group position={[0, 0.049, 0]} rotation={[0, -0.006, 0]} />
              </group>
              <group position={[0, 0.061, 0]} />
            </group>
            <group position={[-0.08, 0.015, 0.013]} rotation={[2.863, -0.005, 0.038]}>
              <group position={[0, 0.123, 0]} rotation={[0.253, 0, 0]}>
                <group position={[0, 0.098, 0]} rotation={[-0.986, 0.028, -0.027]}>
                  <group position={[0, 0.062, 0]} rotation={[2.412, 0, -0.003]} />
                </group>
                <group position={[0, 0.049, 0]} rotation={[0, 0.006, 0]} />
              </group>
              <group position={[0, 0.061, 0]} />
            </group>
            <group position={[0.08, 0.015, 0.013]} rotation={[-1.741, 0, 0]}>
              <group rotation={[-1.679, 0.005, -0.038]} />
              <group rotation={[-1.679, 0.005, -0.038]}>
                <group position={[0, 0.123, 0]} rotation={[0.253, 0, 0]}>
                  <group position={[0, 0.098, 0]} rotation={[-0.986, -0.028, 0.027]} />
                </group>
              </group>
              <group rotation={[-1.679, 0.005, -0.038]} />
            </group>
            <group position={[0.08, 0.015, 0.013]} rotation={[2.863, 0.005, -0.038]} />
            <group position={[0.08, 0.015, 0.013]} rotation={[2.863, 0.005, -0.038]}>
              <group position={[0, 0.061, 0]}>
                <group position={[0, 0.061, 0]} rotation={[0.253, 0, 0]}>
                  <group position={[0, 0.049, 0]} rotation={[0, -0.006, 0]}>
                    <group position={[0, 0.049, 0]} rotation={[-0.986, -0.024, 0.032]} />
                  </group>
                </group>
              </group>
            </group>
            <group position={[-0.08, 0.015, 0.013]} rotation={[-1.741, 0, 0]}>
              <group rotation={[-1.679, -0.005, 0.038]} />
              <group rotation={[-1.679, -0.005, 0.038]}>
                <group position={[0, 0.123, 0]} rotation={[0.253, 0, 0]}>
                  <group position={[0, 0.098, 0]} rotation={[-0.986, 0.028, -0.027]} />
                </group>
              </group>
              <group rotation={[-1.679, -0.005, 0.038]} />
            </group>
            <group position={[-0.08, 0.015, 0.013]} rotation={[2.863, -0.005, 0.038]} />
            <group position={[-0.08, 0.015, 0.013]} rotation={[2.863, -0.005, 0.038]}>
              <group position={[0, 0.061, 0]}>
                <group position={[0, 0.061, 0]} rotation={[0.253, 0, 0]}>
                  <group position={[0, 0.049, 0]} rotation={[0, 0.006, 0]}>
                    <group position={[0, 0.049, 0]} rotation={[-0.986, 0.024, -0.032]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group position={[0, 0.019, 0.254]} rotation={[1.741, 0, 0]}>
            <group position={[0, 0.076, 0]} rotation={[-0.119, 0, 0]}>
              <group position={[0, 0.079, 0]} rotation={[-0.09, 0, 0]}>
                <group position={[0, 0.058, 0]} rotation={[-0.041, 0, 0]}>
                  <group position={[0, 0.105, 0]} rotation={[0.239, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group position={[0, 0.291, -0.012]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, -0.011, 0.116]}>
            <group rotation={[1.623, 0, 0]}>
              <group position={[0, -0.079, 0]} rotation={[-1.623, 0, 0]}>
                <group rotation={[1.741, 0, 0]} />
              </group>
            </group>
          </group>
          <group position={[0, -0.011, 0.116]} rotation={[-0.036, 0, 0]}>
            <group rotation={[1.568, 0, 0]}>
              <group rotation={[0.099, 0, 0]} />
              <group position={[0, 0.058, 0]} rotation={[-1.551, 0, 0]}>
                <group rotation={[1.51, 0, 0]}>
                  <group position={[0, 0.105, 0]} rotation={[0.239, 0, 0]} />
                  <group position={[0, 0.105, 0]} rotation={[-1.501, 0, 0]}>
                    <group rotation={[1.74, 0, 0]}>
                      <group position={[0, 0.025, 0]} rotation={[-1.731, 0, 0]} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group position={[0.332, 0.484, 0.001]} rotation={[0.093, -0.079, -1.89]}>
          <group position={[0.148, -0.096, 0.069]} rotation={[1.243, -0.869, -0.735]} />
        </group>
        <group position={[0.235, 0.525, -0.242]} rotation={[1.682, -0.668, 0.045]} />
        <group position={[-0.332, 0.484, 0.001]} rotation={[0.093, 0.079, 1.89]}>
          <group position={[-0.145, -0.124, 0.017]} rotation={[0.411, 0.781, 1.052]} />
        </group>
        <group position={[-0.235, 0.525, -0.242]} rotation={[1.682, 0.668, -0.045]} />
        <group position={[0.089, 0.047, -0.004]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, -0.046, -0.041]}>
            <group position={[-0.013, 0.079, -0.005]}>
              <group position={[0.027, 0, 0]}>
                <group position={[-0.014, 0, 0]}>
                  <group position={[0, -0.079, 0.005]}>
                    <group position={[0, 0.046, 0.041]} rotation={[-2.412, 0.002, 0.002]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group position={[0.085, 0.143, 0.229]} rotation={[-1.566, 0, -0.001]} />
        <group position={[-0.089, 0.047, -0.004]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, -0.046, -0.041]}>
            <group position={[0.013, 0.079, -0.005]}>
              <group position={[-0.027, 0, 0]}>
                <group position={[0.014, 0, 0]}>
                  <group position={[0, -0.079, 0.005]}>
                    <group position={[0, 0.046, 0.041]} rotation={[-2.412, -0.002, -0.002]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group position={[-0.085, 0.143, 0.229]} rotation={[-1.566, 0, 0.001]} />
        <mesh geometry={nodes.belt.geometry} material={materials.belt} position={[0, 0.367, 0]} />
        <group position={[0, 0.388, 0]}>
          <mesh geometry={nodes.Cube002.geometry} material={materials.body} />
          <mesh geometry={nodes.Cube002_1.geometry} material={nodes.Cube002_1.material} />
        </group>
        <mesh geometry={nodes.boots.geometry} material={nodes.boots.material} position={[0, 0.388, -0.001]} />
        <mesh
          geometry={nodes.bucke_small.geometry}
          material={nodes.bucke_small.material}
          position={[-0.029, 0.361, 0.114]}
          rotation={[0, -0.108, 0]}
        />
        <mesh geometry={nodes.buckle.geometry} material={nodes.buckle.material} position={[0.002, 0.36, 0.112]} />
        <mesh
          geometry={nodes.chestplate.geometry}
          material={nodes.chestplate.material}
          position={[-0.073, 0.535, 0.021]}
        />
        <mesh
          geometry={nodes.chestplate_cape_holder.geometry}
          material={nodes.chestplate_cape_holder.material}
          position={[-0.102, 0.502, 0.093]}
          rotation={[1.421, 0, 0]}
        />
        <mesh
          geometry={nodes.chestplate_shoulder.geometry}
          material={nodes.chestplate_shoulder.material}
          position={[-0.141, 0.536, 0.018]}
          rotation={[0, 0, 0.472]}
        />
        <mesh geometry={nodes.crown.geometry} material={nodes.crown.material} position={[0, 0.777, 0.009]} />
        <mesh geometry={nodes.crown_belt.geometry} material={nodes.crown_belt.material} position={[0, 0.772, 0.009]} />
        <mesh
          geometry={nodes.glove.geometry}
          material={nodes.glove.material}
          position={[-0.331, 0.487, 0.008]}
          rotation={[0, 0, 0.115]}
        />
        <mesh
          geometry={nodes.helmet_inner.geometry}
          material={nodes.helmet_inner.material}
          position={[0, 0.654, 0.009]}
        />
        <mesh
          geometry={nodes.helmet_outer.geometry}
          material={nodes.helmet_outer.material}
          material-color={armorColor}
          position={[0, 0.677, 0.009]}
        />
        <mesh geometry={nodes.tabard.geometry} material={nodes.tabard.material} material-color={clothingColor} position={[-0.07, 0.357, -0.002]} />
      </group>
      <group position={[0.05, 0.377, 0.144]} rotation={[-1.407, -0.727, 0.279]}>
        <mesh geometry={nodes.NurbsPath003.geometry} material={materials.dark} />
        <mesh geometry={nodes.NurbsPath003_1.geometry} material={nodes.NurbsPath003_1.material} />
        <mesh geometry={nodes.NurbsPath003_2.geometry} material={materials.sword_outline} />
        <mesh geometry={nodes.NurbsPath003_3.geometry} material={nodes.NurbsPath003_3.material} material-color={weaponColor}/>
      </group>
      <group position={[0.106, 0.363, -0.202]} rotation={[-3.123, 0.636, -3.048]} scale={[0.125, 0.125, 0.069]}>
        <mesh geometry={nodes.Cube022.geometry} material={nodes.Cube022.material} />
        <mesh geometry={nodes.Cube022_1.geometry} material={nodes.Cube022_1.material} />
      </group>
      {hasCape ?
      <mesh
        geometry={nodes.ss_cape.geometry}
        material={nodes.ss_cape.material}
        position={[-0.157, 0.389, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.783, 0.783, 0.824]}
      />
      :
      <mesh
        geometry={nodes.ss_cape.geometry}
        material={nodes.ss_cape.material}
        position={[-0.157, 0.389, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.0, 0.0, 0.0]}
      />
      }
    </group>
  )
}

useGLTF.preload('/swordShield-transformed.glb')
